- tv.go
- tv_test.go
Implementation of recent additions to API, tagline and aggregate credits for TV.
Manually run the added/modified functions and checked the outputs.
> Add tagline and aggregate credits for TV

- providers.go
- providers_test.go
- tmdb.go
- Adding functions for new endpoints providing lists for watch providers and regions.
https://developers.themoviedb.org/3/watch-providers
- Added tests to the suit
> Add WatchProviders

- movies.go
- tv.go
Not documented but translations for movie and tv also have the `tagline` field.
Tested locally to confirm new fields work.
> Add tagline to movie and tv translations

- genres.go
- movies.go
- networks.go
- people.go
- results.go
- reviews.go
- Added `Adult`, `KnownForDepartment`, `OriginalName` and `Popularity` (documented [here](https://developers.themoviedb.org/3/movies/get-movie-credits))
- Added `Logos` (undocumented)
- Added `Runtime` (mentioned [here](http://www.themoviedb.org/talk/5cb6000cc3a3686b0481f38c#5dfce86026dac100175e1eb3))
- Added `LogoPath` (documented [here](https://developers.themoviedb.org/3/networks/get-network-details))
- Added `Order` (undocumented)
- Added `Official` and `PublishedAt` (documented [here](https://developers.themoviedb.org/3/movies/get-movie-videos))
- Added `OriginCountry` (documented [here](https://developers.themoviedb.org/3/companies/get-company-details))
- Added `Gender` and `KnownForDepartment` (documented [here](https://developers.themoviedb.org/3/people/get-person-details))
- …
> Add missing fields

- movies.go
Simple type name so it's easier to deal with images response
> Extract MovieImage struct

- account.go
> added tmdb avatar

- tv.go
Follow up to #49 
The types used were totally wrong!
- [X ] Bug fix (non-breaking change which fixes an issue)
> use the correct type for TVImages

- collections.go
- companies.go
- networks.go
- people.go
- tv_episodes.go
- tv_seasons.go
This pull goes ahead and expands all of the Image types across the library so that it's all done and they all work the same.
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
> Expand all Image Types

- people.go
- the original_values field is now a string instead of a struct
- the iso_639_1 and iso_3166_1 fields were added to the PersonChanges struct
> people changes

- companies_test.go
- movies_test.go
- tv_episodes_test.go
- tv_seasons_test.go
- tv_test.go
Fix multiple broken tests..
Local. But I'm going to hold thid PR until they fix the API: https://www.themoviedb.org/talk/65b3e54e5541fa0164b18674?language=pt-BR#65c293a0e7c097017dcf0950. Because of this error, 2 tests are failing.
> all tests has been fixed

- README.md
- examples/bearerToken/main.go
- tmdb.go
- tmdb_test.go
Adding the possibility of using bearer tokens.
None.
Feature
> added v4 init function

- README.md
Fixed the casing on `os.Getenv` calls in the README.
N/A
> Update README.md - os.Getenv

- Makefile
- trending.go
- tv_test.go
> tests and warnigs has been fixed

- tv_seasons.go
Add the aggregate credits fields in tv season
In tv Season, add Aggregate Credits fields to support APPEND_TO_RESPONSE
> feat tvseason aggregate credits field

- tv_seasons.go
- tv_seasons_test.go
> TVSeasonDetails add VoteAverage

- README.md
- tmdb.go
- tmdb_test.go
> feature #65: custom base url implemented

- movies.go
- movies_test.go
> MovieDetails add OriginCountry

- movies.go
- tv.go
> fix typo in tv and movie external IDs

- results.go
Add missing field to `TrendingResults`: `media_type`
> add a field named "media_type" to TrendingResults

- movies.go
- results.go
- tv.go
- types.go
Improve the readability of the structure
No test needed.
> Add AlternativeTitle struct

- certifications.go
> Fix certifications
